package backend_for_react.backend_for_react.common.enums;

public enum PermissionType {
    VIEW_ALL_CATEGORIES, RESTORE_CATEGORIES, CREATE_CATEGORIES, MOVE_CATEGORIES, UPDATE_CATEGORIES, DELETE_CATEGORIES, VIEW_DETAIL_CATEGORIES,
    CREATE_ORDER_SHIP, CREATE_RETURN_ORDER_SHIP,
    VIEW_ALL_ORDER, CHANGE_STATUS_ORDER, VIEW_DETAIL_ORDER,
    VIEW_ALL_PRODUCT, CREATE_PRODUCT, UPDATE_PRODUCT, RESTORE_PRODUCT, DELETE_PRODUCT, VIEW_DETAIL_PRODUCT,
    ADD_PRODUCT_VARIANT, UPDATE_PRODUCT_VARIANT, DELETE_PRODUCT_VARIANT,
    VIEW_ALL_USER, CREATE_USER, DELETE_USER, VIEW_DETAIL_USER,
    ADD_PRODUCT_ATTRIBUTE, UPDATE_PRODUCT_ATTRIBUTE, DELETE_PRODUCT_ATTRIBUTE,
    ADD_PRODUCT_ATTRIBUTE_VALUE, UPDATE_PRODUCT_ATTRIBUTE_VALUE, DELETE_PRODUCT_ATTRIBUTE_VALUE, DELETE_PRODUCT_ATTRIBUTE_VALUE_IMAGE,
    ADD_IMAGE_PRODUCT, DELETE_IMAGE_PRODUCT,
    VIEW_ALL_IMPORT_PRODUCT, ADD_IMPORT_PRODUCT, VIEW_DETAIL_IMPORT_PRODUCT, CONFIRM_IMPORT_PRODUCT, CANCEL_IMPORT_PRODUCT, DELETE_IMPORT_PRODUCT_DETAIL, UPDATE_QUANTITY_IMPORT_PRODUCT,
    CHANGE_STATUS_RETURN_ORDER,
    ADD_ROLE, DELETE_ROLE,VIEW_ALL_RETURN_ORDER,
    ADD_SUPPLIER, RESTORE_SUPPLIER, UPDATE_SUPPLIER, DELETE_SUPPLIER, VIEW_DETAIL_SUPPLIER,
    VIEW_ALL_USER_RANK, ADD_USER_RANK, UPDATE_USER_RANK, DELETE_USER_RANK
}
